#generated by ftrain

class ProfessorsViewModel < FreightViewModel

  service :professor

  signal :message
  signal :selected

  attr_reader :list
  
  def initialize
    super
    Thread.new do
      @list = @professor.get_all_professors
      @view.update
      fire :message, "Professors loaded, #{@list.length} records in DB"
    end
  end

  def on_selected(professor)
    fire :selected, professor
  end



end