#generated by ftrain

class ShellViewModel < FreightViewModel

  region :professors
  region :details

  attr_reader :current
  attr_reader :status

  def professors_on_message(message)
    @status = message
    @view.update
  end

  def details_on_message(message)
    @status = message
    @view.update
  end

  def professors_on_selected(professor)
    @status = "Lazy loading missing informations..."
    @view.update
    Thread.new do
    @current = professor
    details.professor_selected(professor)
    @status = "Done."
    @view.update
    end
  end

  def on_quit
    Toolkit.quit
  end

  

end